name: Node.js CI/CD Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# ✅ Prevent overlapping runs (only latest pipeline runs)
concurrency:
  group: nodejs
  cancel-in-progress: true

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package.json') }}
          restore-keys: npm-

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nodejs:latest

  deploy:
    needs: build-test-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to AWS EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Deploying Node.js container on EC2 By Shahzeb..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs:latest
            sudo docker stop nodejs-app || true
            sudo docker rm nodejs-app || true
            sudo docker run -d -p 80:3000 --name nodejs-app ${{ secrets.DOCKER_USERNAME }}/nodejs:latest
